<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-26T20:27:37Z" name="Default Suite" finished-at="2024-08-26T20:28:11Z" duration-ms="33993">
    <groups>
    </groups>
    <test started-at="2024-08-26T20:27:37Z" name="saucedemo" finished-at="2024-08-26T20:28:11Z" duration-ms="33993">
      <class name="MyTests.demoTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:37Z" name="setUp" finished-at="2024-08-26T20:27:41Z" duration-ms="4459" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="sauceTest(java.lang.String)[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:41Z" name="sauceTest" data-provider="dp" finished-at="2024-08-26T20:27:42Z" duration-ms="1211" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user,secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sauceTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:42Z" name="tearDown" finished-at="2024-08-26T20:27:43Z" duration-ms="692" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:43Z" name="setUp" finished-at="2024-08-26T20:27:46Z" duration-ms="2780" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="sauceTest(java.lang.String)[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:46Z" name="sauceTest" data-provider="dp" finished-at="2024-08-26T20:27:46Z" duration-ms="309" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user,secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at MyTests.demoTest.sauceTest(demoTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sauceTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:46Z" name="tearDown" finished-at="2024-08-26T20:27:47Z" duration-ms="662" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:47Z" name="setUp" finished-at="2024-08-26T20:27:50Z" duration-ms="3046" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="sauceTest(java.lang.String)[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:50Z" name="sauceTest" data-provider="dp" finished-at="2024-08-26T20:27:51Z" duration-ms="1081" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user,secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/checkout-step-two.html] but found [https://www.saucedemo.com/checkout-step-one.html]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/checkout-step-two.html] but found [https://www.saucedemo.com/checkout-step-one.html]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at MyTests.demoTest.sauceTest(demoTest.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sauceTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:51Z" name="tearDown" finished-at="2024-08-26T20:27:52Z" duration-ms="706" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:52Z" name="setUp" finished-at="2024-08-26T20:27:54Z" duration-ms="2596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="sauceTest(java.lang.String)[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:27:54Z" name="sauceTest" data-provider="dp" finished-at="2024-08-26T20:28:00Z" duration-ms="6140" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[performance_glitch_user,secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sauceTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:28:00Z" name="tearDown" finished-at="2024-08-26T20:28:01Z" duration-ms="679" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:28:01Z" name="setUp" finished-at="2024-08-26T20:28:04Z" duration-ms="3068" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="sauceTest(java.lang.String)[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:28:04Z" name="sauceTest" data-provider="dp" finished-at="2024-08-26T20:28:05Z" duration-ms="1183" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[error_user,secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/checkout-complete.html] but found [https://www.saucedemo.com/checkout-step-two.html]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/checkout-complete.html] but found [https://www.saucedemo.com/checkout-step-two.html]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at MyTests.demoTest.sauceTest(demoTest.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sauceTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:28:05Z" name="tearDown" finished-at="2024-08-26T20:28:06Z" duration-ms="701" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:28:06Z" name="setUp" finished-at="2024-08-26T20:28:09Z" duration-ms="2692" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="sauceTest(java.lang.String)[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:28:09Z" name="sauceTest" data-provider="dp" finished-at="2024-08-26T20:28:10Z" duration-ms="1202" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[visual_user,secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sauceTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyTests.demoTest@61862a7f]" started-at="2024-08-26T20:28:10Z" name="tearDown" finished-at="2024-08-26T20:28:11Z" duration-ms="676" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- MyTests.demoTest -->
    </test> <!-- saucedemo -->
  </suite> <!-- Default Suite -->
</testng-results>
